#!/bin/sh

#
# Copyright (c) 2011 Alessio Palmero Aprosio <alessio@apnetwork.it>,
#  Universita` degli Studi di Milano
# Copyright (c) 2011 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Postflight script to complete installation.
#

set -e

BASEDIR=/usr/local/share/neubot

logger -s -p daemon.info -t $0 "Neubot basedir: $BASEDIR"

#
# Lookup a valid installed copy of Neubot in the BASEDIR and
# then copy from it.  The loop is written like this for robustness
# but actually there should be just one directory containing the
# freshest Neubot sources etc.
#
for CANDIDATE in $(ls $BASEDIR|sort -rn); do

    CANDIDATE=$BASEDIR/$CANDIDATE
    if [ -d $CANDIDATE -a -f $CANDIDATE/.neubot-installed-ok ]; then

        VERSIONDIR=$CANDIDATE

        logger -s -p daemon.info -t $0 "Neubot versiondir: $VERSIONDIR"

        #
        # If there is another instance of Neubot already installed
        # and we're installing a new fresh copy of Neubot -- ignoring
        # the not-yet-implemented auto-updates -- it's better to
        # stop the old instance so that we successfully start the
        # new instance below.  At the same time, be robust.
        #
        if [ -f /Library/LaunchDaemons/org.neubot.plist ]; then
            launchctl stop org.neubot || true
        fi

        #
        # We're about to run Neubot to setup the database with
        # default privacy permissions.  Before we continue make
        # sure that the environment is ready for Neubot or, if
        # not, prepare it.
        #
        $VERSIONDIR/prerun.sh

        #
        # Match robustly the content of /tmp/neubot-can-share and
        # and setup CAN_SHARE accordingly.
        #
        CAN_SHARE=no

        if [ -f /tmp/neubot-can-share ]; then
            if grep -q '^1$' /tmp/neubot-can-share; then
                    CAN_SHARE=yes
            fi
            rm -f /tmp/neubot-can-share
        fi

        logger -s -p daemon.info -t $0 "Can share: $CAN_SHARE"

        #
        # We don't need to setup any PYTHONPATH because the
        # main.py script should be able to guess its location
        # and adjust its sys.path accordingly.
        #
        logger -s -p daemon.info -t $0 "Initializing privacy settings"

        /usr/bin/python $VERSIONDIR/neubot/main/__init__.py privacy     \
                    -D privacy.init_can_share=$CAN_SHARE                \
                    -D privacy.init_informed=yes                        \
                    -D privacy.init_can_collect=yes                     \
                    -D privacy.overwrite=no

        #
        # Install the property list once and forever; it will invoke
        # BASEDIR/start.sh once at startup.
        #
        logger -s -p daemon.info -t $0 'Installing property list'
        install -m 644 -o root -g wheel $BASEDIR/org.neubot.plist       \
                                         /Library/LaunchDaemons

        #
        # Here we just load org.neubot.plist into launchd(8)
        # and the start org.neubot.  The installation will
        # be completed by the commands referenced into such
        # plist file.  The rationale is that both the install
        # and the auto-update must finalize the procedure
        # adding symlinks etc.  So better to put all the logic
        # into the same place, and that cannot be this file
        # because it is run only on the first install.
        #
        logger -s -p daemon.info -t $0 "Loading neubot via launchctl(1)"

        launchctl load /Library/LaunchDaemons/org.neubot.plist
        launchctl start org.neubot

        # Success!
        exit 0

    fi
done

# Should not happen!
logger -s -p daemon.error -t $0 'No candidate Neubot'
exit 1
