#!/bin/sh

#
# Copyright (c) 2011 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Abort the installation if for some reason /tmp/neubot-can-share
# is not there: this possibly means that the Privacy pane failed to
# load for whathever reason.
# We cannot do that in the postflight for obvious reasons.
#

set -e

if ! [ -f /tmp/neubot-can-share ]; then
	logger -p daemon.info -t $0 "Missing /tmp/neubot-can-share"
	exit 1
fi
