#!/bin/sh

#
# Copyright (c) 2010 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Start neubot web interface (and possibly neubot itself)
#

debug() {
	: echo "neubot: " $@ 1>&2
}

#
# Try to find a suitable version of Python.  Take into account user
# preferences.  Check whether the user have manually installed Python.
# By default, use system Python (this should work for versions of
# MacOs >= 10.5).
# FIXME The problem with Pythons different from the default one is
# that neubot would not be able to re-exec self because /bin/neubot
# shebang line is #!/usr/bin/env python.  Therefore, the system
# Python is used to re-exec and this means that neubot might not
# be able to start the daemon.
#

is_good() {
	if [ -x $1 ]; then
		version=`$1 -V 2>&1|awk '{print $2}'`
		major=`echo $version|awk -F. '{print $1}'`
		minor=`echo $version|awk -F. '{print $2}'`
		if [ $major -eq 2 -a $minor -ge 5 ]; then
			debug "python: ver=$version; bin=$1"
			rv=0
		else
			rv=1
		fi
	else
		rv=1
	fi
	return $rv
}

BEST_PYTHON=""
# FIXME See above
#LIST="$LIST $NEUBOT_PYTHON"
#LIST="$LIST /Library/Frameworks/Python.framework/Versions/Current/bin/python"
LIST="$LIST /usr/bin/python"
for ITEM in $LIST; do
	is_good $ITEM
	if [ $? ]; then
		BEST_PYTHON=$ITEM
		break
	fi
done
if [ "$BEST_PYTHON" = "" ]; then
	echo "neubot: fatal: can't find python" 2>&1
	exit 1
fi

#
# Find out the place where neubot.app/ is installed and adjust
# Python path to include neubot sources.
#

BASE=`echo $0|sed 's/\/MacOS\/neubot//'`
NEUBOT=$BASE/Resources/neubot
export PYTHONPATH=$NEUBOT:$PYTHONPATH

debug $BEST_PYTHON $NEUBOT/bin/neubot
$BEST_PYTHON $NEUBOT/bin/neubot
