# Makefile

#
# Copyright (c) 2011 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

.PHONY: update

update:
	@inkscape -e neubot-16x16.png --export-width=16 \
	          --export-height=16 neubot.svg
	@inkscape -e neubot-32x32.png --export-width=32 \
	          --export-height=32 neubot.svg
	@inkscape -e neubot-48x48.png --export-width=48 \
	          --export-height=48 neubot.svg
	@inkscape -e neubot-64x64.png --export-width=64 \
	          --export-height=64 neubot.svg
	@inkscape -e neubot-128x128.png --export-width=128 \
	          --export-height=128 neubot.svg
	@inkscape -e neubot-256x256.png --export-width=256 \
	          --export-height=256 neubot.svg
