#!/bin/sh

#
# Copyright (c) 2010 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

### BEGIN INIT INFO
# Provides: neubot
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Network neutrality bot (neubot)
### END INIT INFO

case $1 in
    "start")
        echo "Starting neubot: /usr/bin/neubot start"
        /usr/bin/neubot start
        ;;
    "stop")
        echo "Stopping neubot: /usr/bin/neubot stop"
        /usr/bin/neubot stop
        ;;
    "restart")
        /etc/init.d/neubot stop
        sleep 1
        /etc/init.d/neubot start
        ;;
    *)
        echo "Usage: $0 start|stop|restart"
        ;;
esac
