#!/bin/sh

# etc/init.d/neubot
# Copyright (c) 2010 NEXA Center for Internet & Society

# This file is part of Neubot.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.

case $1 in
    "start")
        if [ -f /var/run/neubot.pid ]; then
            PID=`cat /var/run/neubot.pid`
            if kill -0 $PID; then
                echo "error: neubot already running with pid $PID."
                exit 1
            fi
        fi
        echo "Starting neubot: /usr/bin/neubot -b"
        /usr/bin/neubot -b
        ;;
    "stop")
        if [ -f /var/run/neubot.pid ]; then
            PID=`cat /var/run/neubot.pid`
            if kill -0 $PID; then
                echo "Stopping neubot: kill -QUIT $PID"
                kill -QUIT $PID
            fi
            rm -rf /var/run/neubot.pid
        fi
        ;;
    "restart")
        /etc/init.d/neubot stop
        sleep 1
        /etc/init.d/neubot start
        ;;
    *)
        echo "Usage: $0 start|stop|restart"
        ;;
esac
