#!/usr/bin/env python

#
# Copyright (c) 2011 Marco Scopesi <marco.scopesi@gmail.com>,
#  Politecnico di Torino
# Copyright (c) 2011 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

'''
 Embed WebKit into a simple Gtk window to provide users with
 a real Neubot application.  This script is designed to enhance
 user experience under Ubuntu.  But in principle you can use
 it wherever gtk and webkit bindings are installed.
'''

import gtk 
import webkit 
import os.path
import getopt
import sqlite3
import sys

if sys.version_info[0] == 3:
    import http.client as lib_http
else:
    import httplib as lib_http

STATIC_PAGE = '''\
<HTML>
 <HEAD>
  <TITLE>Neubot 0.4.2 -- Neubot is not running</TITLE>
 <HEAD>
 <BODY>
  <H1>Neubot 0.4.2 -- Neubot is not running</H1>
  <P>
   If you see this page it means that the Neubot daemon is not
   running on your system.  This is likely a bug and you should
   inform Neubot authors about that, using Neubot
   <A href='http://www.neubot.org/mailing-lists'>mailing list</A>.
  </P>
 </BODY>
</HTML>
'''

ICON = '/usr/share/icons/hicolor/scalable/apps/neubot.svg'
if not os.path.isfile(ICON) or not os.access(ICON, os.R_OK):
    ICON = None

class Viewer(gtk.Window):

    ''' Embed webkit.WebView into gtk.Window '''

    def __init__(self, width, height, uri):

        ''' Initialize the window '''

        gtk.Window.__init__(self)

        scrolledwindow = gtk.ScrolledWindow() 
        self._webview = webkit.WebView() 
        scrolledwindow.add(self._webview)
        self.add(scrolledwindow)

        if ICON:
            self.set_icon_from_file(ICON)

        self.set_title('Neubot 0.4.2')
        self.connect('destroy', gtk.main_quit)
        self.maximize()
        self._open_web_page(uri)

        self.show_all()

    def _open_web_page(self, target):
        ''' Open the specified web page '''

        #
        # Target is a URI when we know that Neubot is running
        # and a static page otherwise.
        #

        if target.startswith('http://'):
            self._webview.open(target)
        else:
            self._webview.load_string(target, 'text/html', 'utf-8', '')

def main(args):

    ''' Entry point for simple gtk+webkit GUI '''

    database = '/var/neubot/database.sqlite3'
    address, port = '127.0.0.1', '9774'

    # Get command line options
    try:
        options, arguments = getopt.getopt(args[1:], 'f:')
    except getopt.error:
        sys.exit('Usage: neubot-webkit-gui [-f database]\n')
    if arguments:
        sys.exit('Usage: neubot-webkit-gui [-f database]\n')

    # Read command line options
    for name, value in options:
        if name == '-f':
            database = value

    # Read system-wide neubot settings
    connection = sqlite3.connect(database)
    cursor = connection.cursor()
    cursor.execute('SELECT * FROM config;')
    for name, value in cursor:
        if name == 'agent.api.address':
            address = value
        elif name == 'agent.api.port':
            port = value
    connection.close()

    # Test if neubot deamon is running
    uri = STATIC_PAGE
    try:
        connection = lib_http.HTTPConnection(address, port)
        connection.request('GET', '/api/version')
        response = connection.getresponse()
        if response.status == 200:
            uri = 'http://%s:%s/' % (address, port)
        response.read()
        connection.close()
    except:
        pass

    # Start the GUI      
    Viewer(800, 600, uri)
    gtk.main()

if __name__ == '__main__':
    main(sys.argv)
