#!/usr/bin/python

#
# Copyright (c) 2011 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

#
# This is SAME AS the standard bin/neubot _but_ employs
# /usr/bin/python instead of /usr/bin/env python so we are
# sure that we pick the system python.  This is safe
# because, under Debian, Neubot depends on python >= 2.5.
#

import sys
import os

NEUBOT_HOME = "/usr/share"
if NEUBOT_HOME.startswith("@"):
    NEUBOT_HOME = "."

if os.environ.has_key("NEUBOT_HOME"):
    NEUBOT_HOME = os.environ["NEUBOT_HOME"]
sys.path.insert(0, NEUBOT_HOME)

from neubot.main import main
main(sys.argv)
