#!/usr/bin/env python

#
# Copyright (c) 2011-2012 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

''' Neubotw.exe on Windows '''

import sys

from neubot.main_win32 import main
from neubot.log import LOG

#
# Redirect the logger immediately because we're going to run in
# windows mode and therefore there is neither a console nor a standard
# error for the default logger.  The logs are available in the proper
# tab of the Web User Interface (WUI) or via the API.
#
LOG.redirect()

main(sys.argv)
