#!/bin/sh -e

#
# Copyright (c) 2011 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Make sure that there is conflict between the normal package
# and the -nox flavor.
#

test -x /usr/bin/dpkg || exit 0

if dpkg -l | grep -q neubot; then
    echo "$0: you must uninstall Neubot to run this test" 1>&2
    exit 1
fi
if [ `id -u` -ne 0 ]; then
    echo "$0: you must be root to run this test" 1>&2
    exit 1
fi

VER=0.4.13-rc4

echo 'BEGIN: Create debian package...'
test -f dist/neubot-$VER-1_all.deb || { make clean; make deb; }
echo 'END: Create debian package (OK)'

echo 'BEGIN: Install debian package...'
dpkg -i dist/neubot-$VER-1_all.deb
echo 'END: Install debian package (OK)'

echo '*** Please close the notification window...'
sleep 15

echo 'BEGIN: Try to install -nox package...'
dpkg -i dist/neubot-nox-$VER-1_all.deb && exit 1
echo 'BEGIN: Try to install -nox package (OK)'

echo 'BEGIN: Cleanup...'
dpkg --purge neubot
test -f /var/neubot/database.sqlite3 && exit 1
echo 'END: Cleanup (OK)'

echo 'BEGIN: Install the -nox package...'
dpkg -i dist/neubot-nox-$VER-1_all.deb
echo 'END: Install the -nox package (OK)'

echo '*** Please close the notification window...'
sleep 15

echo 'BEGIN: Try to install the normal package...'
dpkg -i dist/neubot-$VER-1_all.deb && exit 1
echo 'BEGIN: Try to install the normal package (OK)'

echo 'BEGIN: Cleanup...'
dpkg --purge neubot-nox
test -f /var/neubot/database.sqlite3 && exit 1
echo 'END: Cleanup (OK)'
