#!/bin/sh

#
# Copyright (c) 2009 The Chromium Authors.
# Copyright (c) 2011 Simone Basso <bassosimone@gmail.com>.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer
#      in the documentation and/or other materials provided with the
#      distribution.
#
#    * Neither the name of Google Inc. nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# Stripped-down version of /etc/cron.daily/google-chrome, which
# reenables the repository if it was disabled during and upgrade,
# but does not touches it if the user disabled it manually.
# The user knows, the user rules.
# I'm sure it does not address all the corner cases but I don't
# understand why people should customize their debian setup that
# much.
# The original chrome code was looking for an english comment
# at the end of the script.  However I just found that the Italian
# Ubuntu appends a comment in italian.  To write robust code I
# have no choice but to look for a line followed by ANY comment.
#

SOURCELIST='/etc/apt/sources.list.d/neubot.list'
REPOCONFIG='deb http://releases.neubot.org/ /'

logger -t $0 -p user.debug \
'Checking whether Neubot repository needs to be enabled'

grep -qE \
"^[[:space:]]*#[[:space:]]*$REPOCONFIG[[:space:]]*#.*" \
"$SOURCELIST"

if [ $? -eq 0 ]; then
    logger -t $0 -p user.notice 'Reenabling Neubot repository after upgrade'
    cp $SOURCELIST $SOURCELIST.save
    echo '#' > $SOURCELIST
    echo '# WARNING! IF YOU WANT TO DISABLE NEUBOT REPOSITORY' >> $SOURCELIST
    echo '# PLEASE DO NOT APPEND COMMENTS TO THE REPOS LINE.' >> $SOURCELIST
    echo '#' >> $SOURCELIST
    echo '# See <http://www.neubot.org/disable-repository>' >> $SOURCELIST
    echo '# for an explanation.' >> $SOURCELIST
    echo '#' >> $SOURCELIST
    echo $REPOCONFIG >> $SOURCELIST
else
    logger -t $0 -p user.debug 'No need to reenable Neubot repository'
fi
