#!/bin/sh

#
# Copyright (c) 2011 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Script to assemble the phrase I usually add to release
# announce.
#

test $# -eq 2 || {
    echo 'Usage: scripts/diffstat start stop' 1>&2
    exit 1
}

PATCHES=$(git log --oneline $1..$2|wc -l)

printf "This release contains %d patches." $PATCHES

DIFFSTAT=$(git diff --stat $1..$2|tail -n1)
CHANGED=$(echo $DIFFSTAT|awk '{print $1}')
INSERTED=$(echo $DIFFSTAT|awk '{print $4}')
DELETED=$(echo $DIFFSTAT|awk '{print $6}')

printf "  The diffstat says: $CHANGED files\n"
printf "changed, with $INSERTED lines inserted and $DELETED lines deleted.\n"
