#!/bin/sh

#
# Copyright (c) 2012 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Auto-generate FAQ pages
#

if [ -z $rst2html ]; then
    rst2html=/usr/bin/rst2html
fi

faq_filter() {
    ./scripts/faq_filter "$(date)" "$(git describe --tags)"
}

for file in doc/FAQ.rst doc/FAQ-it.rst; do
    ofile=$(echo $file|sed 's/\.rst$/.html/g')
    $rst2html $file | faq_filter > $ofile
done
