#!/usr/bin/env python

#
# Copyright (c) 2013
#     Nexa Center for Internet & Society, Politecnico di Torino (DAUIN)
#     and Simone Basso <bassosimone@gmail.com>
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

""" Generates the FAQ's index from doc/faq.md """

import sys

def slugify(line):
    """ Significantly simplify the line """
    accum = []
    for char in line:
        if char.isupper():
            accum.append(char.lower())
        elif char.islower():
            accum.append(char)
        elif char.isdigit():
            accum.append(char)
        elif char.isspace():
            accum.append("-")
        elif char == "-":
            accum.append(char)
    return "".join(accum)

def main():
    """ Main function """

    filep = open("doc/faq.md", "r")
    prevline = ""
    lines = []
    for line in filep:
        if (line.startswith("=====") or line.startswith("-----")) and prevline:
            lines.append(prevline)
        prevline = line
    filep.close()

    for line in lines:
        line = line.strip()
        if not line:
            continue
        if not line[0].isdigit():
            continue
        index = line.find(".")
        if index < 0:
            continue
        if line[index + 1].isdigit():
            indent = "    "
        else:
            indent = ""
        sys.stdout.write("%s- [%s](#%s)\n" % (indent, line, slugify(line)))

if __name__ == "__main__":
    main()
