#!/bin/sh

#
# Copyright (c) 2010 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Make sure there is not garbage around
#
./scripts/cleanup

#
# Get current version number
# Note: the two char classes below contain a space and a tab
#
CURRENT=`grep ^VERSION Makefile | sed 's/^VERSION[ 	]*=[ 	]*//'`
CURRENT_MAJOR=`echo $CURRENT | cut -d. -f1`
CURRENT_MINOR=`echo $CURRENT | cut -d. -f2`
CURRENT_PATCH=`echo $CURRENT | cut -d. -f3`

#
# Compute new version number
#
if [ $# -eq 1 ]; then
    NEW=$1
else
    printf "Usage: %s new-version\n" $0 1>&2
    exit 1
fi

#
# Update ChangeLog.
#
DATE=`date +%F`
printf "Neubot $NEW [$DATE]\n" > ChangeLog.in
git log --oneline --reverse --format="%x09* %s" $CURRENT..HEAD >> ChangeLog.in
printf "\t* Release neubot/$NEW\n\n" >> ChangeLog.in
cat ChangeLog >> ChangeLog.in
mv ChangeLog.in ChangeLog

#
# Update the numeric representation first because
# libversion.py has the current canonical version
# number written into its code.  So if we update
# the canonical repr first the code below would
# not work.
#
PATTERN=$(python neubot/libversion.py)
NEW_NUMERIC=$(python neubot/libversion.py $NEW)
FILES=`grep -Rn $PATTERN *|grep -v ^ChangeLog|awk -F: '{print $1}'|sort -u`
for FILE in $FILES; do
    ./scripts/sed_inplace s/$PATTERN/$NEW_NUMERIC/g $FILE
done

#
# Update version number.
# Make sure we don't touch the ChangeLog.
# We don't assume `sed -i' is valid.
#
PATTERN=`./scripts/new_version.py $CURRENT`
FILES=`grep -Rn $PATTERN *|grep -v ^ChangeLog|awk -F: '{print $1}'|sort -u`
for FILE in $FILES; do
    ./scripts/sed_inplace s/$PATTERN/$NEW/g $FILE
done

#
# Commit
#
git commit -a -m "Release neubot/$NEW"
git tag $NEW
