#!/bin/sh

#
# Copyright (c) 2011 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

if [ $# -lt 2 ]; then
    echo "Usage: sed_inplace PATTERN FILE ..." 1>&2
    exit 1
fi

#
# The `cat $1.tmp > $1` part below is because we want to
# retain the original permissions of $1.  This is paramount
# or we'll ship a non-executable $(PREFIX)/bin/neubot.
#

P=$1
shift

while [ $1 ]; do
    { sed "$P" $1 > $1.tmp && cat $1.tmp > $1 && rm $1.tmp; } || exit $?
    shift
done
