#!/bin/sh

#
# Copyright (c) 2011 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

if env sha1sum </dev/null >/dev/null 2>/dev/null; then
    sha1sum $@
elif env cksum </dev/null >/dev/null 2>/dev/null; then
    for FILE in $@; do
        CKSUM=`cat $FILE|cksum -a sha1` && echo "$CKSUM  $FILE"
    done
else
    echo "error: can't calculate sha1sum" 1>&2
    exit 1
fi
