#!/bin/sh -e

#
# Copyright (c) 2012 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Sign all packages.  (Currently it just signs M-Lab automatic
# updates, but the idea is to sign all, hence the name.)
#

# Fetch configuration and especially location of PRIVKEY
. $HOME/.neubot-sign-all

openssl_sign() {
    echo "sign_all: $1" 1>&2
    /usr/bin/openssl dgst -sha256 -sign $PRIVKEY -out $1.sig $1
}

while [ $# -gt 0 ]; do
    openssl_sign $1
    shift
done
