#!/bin/sh

#
# Copyright (c) 2010 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Update ChangeLog.
# Adapted from scripts/release.
#

if [ $# -eq 2 ]; then
    CURRENT=$1
    NEW=$2
else
    printf "Usage: %s old-version new-version\n" $0 1>&2
    exit 1
fi

DATE=`date +%F`
printf "Neubot $NEW [$DATE]\n" > ChangeLog.in

if [ -z `git tag|grep $NEW` ]; then
    TIP=HEAD
else
    TIP=$NEW
fi

git log --oneline --reverse --format="%x09* %s" $CURRENT..$TIP >> ChangeLog.in

if [ -z `git tag|grep $NEW` ]; then
    printf "\t* Neubot/$NEW released\n\n" >> ChangeLog.in
else
    printf "\n" >> ChangeLog.in
fi

cat ChangeLog >> ChangeLog.in
mv ChangeLog.in ChangeLog
