#!/bin/sh

#
# Copyright (c) 2011 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

if [ -x /usr/bin/dpkg-scanpackages ]; then
    {
        cd dist &&
        dpkg-scanpackages . > Packages &&
        gzip --stdout -9 Packages > Packages.gz &&
        cp ../Debian/Release . &&
        for FILE in Packages Packages.gz; do
            {
                SHA256SUM=`sha256sum $FILE | awk '{print $1}'` &&
                KBYTES=`wc -c $FILE | awk '{print $1}'` &&
                echo " $SHA256SUM $KBYTES $FILE" >> Release;
            }
            test $? || exit 1
        done &&
        gpg -abs -o Release.gpg Release;
    }
    test $? || exit 1
else
    echo "warning: could not update apt: dpkg-scanpackages not available" 1>&2
fi
