#!/bin/sh -e

#
# Copyright (c) 2009 The Chromium Authors.
# Copyright (c) 2010 Simone Basso <bassosimone@gmail.com>.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer
#      in the documentation and/or other materials provided with the
#      distribution.
#
#    * Neither the name of Google Inc. nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# This function is lifted from Google Chrome's
# /etc/cron.daily/google-chrome script.
#
install_key() {
  APT_KEY="`which apt-key 2> /dev/null`"
  if [ -x "$APT_KEY" ]; then
    "$APT_KEY" add - >/dev/null 2>&1 <<KEYDATA
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.10 (GNU/Linux)

mQMuBEwOZBERCAC6Hs/+xjJQXu2whf3jsPCHGzHsG9bcLAN80CvsGuSMsiqpCDOr
HQ7ET5W5Kk/kzf6K9orbKDE1K65SAqbDt2TIxBgvBzgDaDaUNTUWvdx+4r7AXnxe
Jq0wlg4VL/RQ0InHCtmE3dmQTZh5d/kBdbRpc8h3NlDUKRHCzqkHZqUlgK64yM5v
Y0Qm6TYIlnuZr85OrB9TcqzaAOtbQR/1uZ/Tz//OTrstSGa95ZvSuotaeu93chS3
JZ/KjggdDRzhoRLjcYh/y1o//y39w+p7btjvZ7rOsEg/yfnWkEY6aUKyF+jw5miK
deHdif5bqVPsSbHdrNkC0I1j+ZtT2MUxmDiLAQC+B7wepNhNWLUGOvVRLAAdgfqj
Hen21IvTGwvSsgLKYQgAlKKW4AwgxI5oJAAoTqXAgocn13x9SM9hMITtCADeMEvW
EYSKTTAqNX6PQH2wDx2KoiBQ+mBo9MAs1nXT+ikkDfjWhiUdkD/L4lU0z/JEMLC4
A3e1DRF31kfH2WYGmxGoBGeCDq612BBk5i/V2lYsQj4kdcc/LUyzH4rhAXV5I3x4
aMn0WH3E2/JJpFZMLcC6tV6Wui1Zy4+pmAovL1E44LMWc8imogvrNTuPqll/X8fY
lFGXXCHTKZ6mtkwgCRz1feO2yXBZstjvF3pE2rFzIRdEjUlrL62HMr+MAJDtnv6e
kowF4+1jx9nCskKbx2XIDGkOwEYAmISBdQiiqTuVdwgAguEFbg4TnTY8v8Y8DrDv
mQdRVQVQswPT8p1eGOZbw6Q8SX+MOu3/Mah+xz9Tj+qUkgAVGmvAoV86opfYESZF
wrMDSShPGsIhnaJCoN6rlJtfUfgpeiNCQ4cty5g7iL9TUuKAOFBXlk6B0AVLP5TU
vVbCaYxUY7Q6lBvd8j/M5Tk9b4mqAx1itLtWTJYabrEkgiEA0zgILVsHtl3SwHO5
vjElPNwYUpkKNIbKnLja52xvJd0FOGF84WWklEHTkaVmCfvf9IyectzZtFM4wubU
D6C0E2eXwfO32YunCH4QfWrrE0kaovo9WCpqPwJGokmuZDkbVKZnQ6In7eQOI2IR
OrQkU2ltb25lIEJhc3NvIDxiYXNzb3NpbW9uZUBnbWFpbC5jb20+iHoEExEIACIC
GwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheABQJN8m2gAAoJEJX5anr2jRqtieEB
ALvAaB+DrsUqr3+yq6tiq+LrOpyGUYdowktXJk/abZADAP471Gk9EX9rjPjdPs+0
0LuHt2TsfBVFLMUR3h2pT+t0UQ==
=hI5l
-----END PGP PUBLIC KEY BLOCK-----
KEYDATA
  fi
}

python -m compileall -q /usr/share/neubot
if ! grep -q _neubot /etc/group; then
    groupadd -r _neubot
fi
if ! grep -q _neubot /etc/passwd; then
    useradd -r -d/ -g_neubot -s/usr/sbin/nologin _neubot
fi
update-rc.d neubot defaults 99
install_key

#
# Privacy
#

if ! /usr/bin/neubot privacy -t; then
    if [ -d /var/lib/update-notifier/user.d/ ]; then
        rm -rf /var/lib/update-notifier/user.d/neubot
        cat << EOF >> /var/lib/update-notifier/user.d/neubot
Name: Neubot privacy settings
Priority: High
Terminal: False
Command: /usr/bin/neubot viewer
Description: Starting from version 0.4.6 Neubot servers are deployed on
 the distributed Measurement Lab (M-Lab) platform.  To comply with
 M-Lab policy and be allowed to run tests, Neubot needs to ask you the
 permission to collect and publish your Internet address.
 To read the privacy policy and provide the permissions, please click to
 the button below, which will open Neubot GUI, or point directly your web
 browser to <http://127.0.0.1:9774/>.
EOF
        touch /var/lib/update-notifier/dpkg-run-stamp
    fi
fi

#
# Startup neubot at the end to avoid races
# with the privacy command above.
# XXX Redirect standard error to /dev/null or
# neubot does not actually start.
#
invoke-rc.d neubot start 2>/dev/null
