#!/bin/sh

#
# Copyright (c) 2010 Simone Basso <bassosimone@gmail.com>,
#  NEXA Center for Internet & Society at Politecnico di Torino
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

set -e
if [ -x /usr/bin/pkill ]; then
	/usr/bin/pkill -KILL -f 'neubot statusicon' || true
	/usr/bin/pkill -KILL -f 'neubot on_gui_login' || true
fi
if [ -f /etc/init.d/neubot ]; then
	/etc/init.d/neubot stop
	update-rc.d -f neubot remove
fi
if [ -d /usr/share/neubot ]; then
	find /usr/share/neubot -type f -name \*.pyc -exec rm -rf {} \;
fi
if grep -q _neubot /etc/passwd; then
	userdel _neubot
fi
if grep -q _neubot /etc/group; then
	groupdel _neubot
fi
